### ISSUE TITLE
Deviation between map data and OSM

### ISSUE THREAD

**Issue by wowlza** [nutonomy/nuscenes-devkit#1010]
Hi, 
I'm trying to obtain SD maps from OpenStreetMap(OSM) based on the map data.  But I had a problem with deviation between map data and OSM data.

I want to know how to correct such deviations?

I got the OSM data according to the following steps:

1. get the pose information from each scene, and from this, the corresponding frame_pose is obtained. 
2. get the max_x, max_y, min_x, min_y according to the frame_pose,  and get the area of maps.  
```      
         try:
            area = np.array([
            [min_x-180, min_y-180],
            [max_x+180, max_y+180]])
         except:
            area = np.array([
            [min_x-130, min_y-130],
            [max_x+130, max_y+130]])
```
3.  convert the 4 maps from city_coords to utm(EPSG: 3857)
`projector = Proj(proj="utm", zone=utm_zone, ellps="WGS84", datum="WGS84", units="m")`
4. convert the 4 maps from utm to wgs84 ( EPSG:4326 )
5. download the OSM data according to the latitude and longitude.

I vitualized the maps and there is a certain bias in the results, especially the boston-seaport.
The results are as following:

The gray lines are roads from OSM and the gray blocks are road_segment and lane from nuScenes 

![图片4](https://github.com/nutonomy/nuscenes-devkit/assets/114270963/533f9010-4ead-42a3-b6ce-33fec9c1926d)

The deviation is noticeable in the upper left corner of the image
![图片1](https://github.com/nutonomy/nuscenes-devkit/assets/114270963/a3ab05bd-297c-49c0-b060-bc6b56818cf9)

![图片2](https://github.com/nutonomy/nuscenes-devkit/assets/114270963/98956112-d9b5-4a5a-91d3-107039830d33)

![图片3](https://github.com/nutonomy/nuscenes-devkit/assets/114270963/ab34dfb2-110a-43b7-a83e-f61d96e68141)

**Comment by whyekit-motional** [comment]
@wowlza pls see if this helps you: https://github.com/nutonomy/nuscenes-devkit/issues/966

**Comment by wowlza** [comment]
@whyekit-motional Thank you for the fast response.
I did it on [966](https://github.com/nutonomy/nuscenes-devkit/issues/966)

**Comment by wowlza** [comment]
@whyekit-motional Thanks for fast response.
But I think [#966](https://github.com/nutonomy/nuscenes-devkit/issues/966) did not solve my problem.

[#966](https://github.com/nutonomy/nuscenes-devkit/issues/966) visualize the results in EPSG 3857 or EPSG 4326, but I visualized my result under the city coordinates.

The method I got the OSM data can be demonstrated by the following image:
![坐标转换思路](https://github.com/nutonomy/nuscenes-devkit/assets/114270963/f77a71dc-95d6-4efe-90e7-582462c5fcaf)

As I demonstrated before, I got the city_coords according to the frame_pose, which is measured in **meters**.  

Therefore,  in order to get the absolute coordinates, **I have to use the UTM coordinate system as an intermediary**.

I first converted the original coordinates of the city EPSG:4326, like singapore-onenorth: (1.2882100868743724, 103.78475189208984), to EPSG:3857.  In the EPSG:3857 coordinates, the values of the city coordinate are added on the basis of the original coordinates.  Then I converted it back to EPSG 4326, and got the OSM data.

The steps to convert back are also consistent.

Did I make any mistakes along the way? Could you give me some advice?
Thanks!

**Comment by basbaba** [comment]
Many people mailed me about the coordinates of nuScenes problem. I'll make it more clear:

1. nuScenes raw data captured by GNSS is under EPSG:4326, this is a **Spherical coordinate system** , described as latitude, longitude and altitude(LLA), it's unit is degree

2. When drawing the raw data on nuScenes Map, this is a projection, we called it: ﻿﻿**Local tangent plane coordinates (LTP)**, in most case also as **east, north, up (ENU)**, it's unit is meter
[https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates](url)

3. because each map of nuScenes is small(about 3km x 3km), so we can take is as a rectangle plane, not a curve surface on spherical, so it's easy to calculate distance and angle on these maps

4. The detail of transferring between ENU and EPSG:4326 or EPSG:3857 is like this:
ENU <-> ECEF <-> EPSG:4326 <-> EPSG:3857
ECEF is **Earth-centered, Earth-fixed coordinate system**
[https://en.wikipedia.org/wiki/Earth-centered,_Earth-fixed_coordinate_system](url)

ENU and EPSG:3857 are 2D Cartesian coordinate system
ECEF is 3D Cartesian coordinate system

5. there is a good tool to do these convertion, I got them from:
[https://github.com/mapillary/OpenSfM/blob/main/opensfm/geo.py](url)
[https://github.com/facebookresearch/OrienterNet/blob/main/maploc/utils/geo.py#L79](url)
You can easily migrate the 2 files into your project.
The Class Projection can be used to do:
ENU(X,Y) <-> ECEF(X,Y,Z) <-> EPSG:4326(LLA)

7. I just used these resource to integrate nuScenes Map and OSM

Hope this can help you
