### ISSUE TITLE
potential bug in algo.py while using dist_fcn parameter

### ISSUE THREAD

**Issue by tonmoy-saikia** [nutonomy/nuscenes-devkit#1027]
Hi, I noticed that the `accumulate` function uses `dist_fcn` to parameterize the matching cost. But the stored matching errors use `center_distance` (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/algo.py#L101C44-L101C59). Shouldn't this be `dist_fcn`?

**Comment by whyekit-motional** [comment]
@tonmoy-saikia I think using `center_distance(...)` to calculate `match_data['trans_err']` is correct, since `trans_err` is meant to store the difference in the center of the matched predicted box from that of the GT box

On the other hand, `dist_fcn` is used to determine whether the predicted box matches any GT boxes in the first place
