### ISSUE TITLE
Calibrated_sensors location

### ISSUE THREAD

**Issue by giladdiv** [nutonomy/nuscenes-devkit#108]
1.It is written that the translation and the rotation parameters are given with respect to the ego vehicle body frame, what is the [0,0,0] location? I thought that it is the center of the 3D bounding box (the same as the reference point to the translation values for the ego_pose and other objects) but the numbers doesn't add up.
2.The translation of the sensors are written as [l,w,h] ?
3. The rotation of the ego_pose and other objects rotation is relative to which axis? are they all written at the same coordinate system?

**Comment by holger-nutonomy** [comment]
1. [0, 0, 0] refers to the "ego vehicle body frame". That is a point in the center of the rear axle (where the IMU is located). Hence it is neither the location of the lidar nor the center of the bounding box (which could sometimes be inaccurate).
2. Please refer to the [schema](https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md). Translation is stored as [x, y, z], sizes are stored as [w, l, h]. z is pointing up here, x and y correspond to lat and lon in the map. Units are meters.
3. To see the different coordinate frames, refer to the figure at: https://www.nuscenes.org/data-collection . In practice it is often easier to use our provided code rather than figuring it out for yourself. E.g. [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L201) is the function that loads annotations and transforms them into the specified sensor coordinate frame.
