### ISSUE TITLE
Same route, different time/weather?

### ISSUE THREAD

**Issue by AnneCCollin** [nutonomy/nuscenes-devkit#118]
Hi,

Is there an overview of the scenes (beyond nusc.list_scenes) that would enable the user to know which scenes correspond to the same route, just at a different time or under different weather conditions? I see the "singapore-onenorth" field for example, but there are multiple routes that the car took in scenes under this description.

(Based on your familiarity with the dataset, if you have a couple of scenes you already know correspond to the same route under different weather, that would be great!)

**Comment by holger-nutonomy** [comment]
Hi, we use several dozen "routes", but since a scene is only 20s the fact that two scenes are from the same route does not necessarily mean that they are from a similar location. I suggest instead to look at the `translation` of `ego_pose`. The translation defines an x/y/z point in the local map coordinates (in meters). Then you can just use some heuristics to find close-by scenes.
As a related example, take a look at [this function](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L1062), which renders the number of ego poses within 100m. Output should look similar to this (although that image only uses teaser data): https://www.nuscenes.org/public/images/gallery-4.jpg
