### ISSUE TITLE
Automatically take into account new tables

### ISSUE THREAD

**Issue by chocojoX** [nutonomy/nuscenes-devkit#167]
When converting the 3D boxes into 2D boxes, we obtain a new file (named by default `image_annotations.json`). Currently, however, this data is not taken into account in the nuScenes dataset created with the command `NuScenes(version='v1.0-mini', dataroot=data_root, verbose=True)`.
I believe that automatically adding all available tables, if they meet the formatting requirements, would be a _nice to have_ .

Thanks for your work :)

**Comment by HazemEssamAli** [comment]
Hello,

I always receive an error when I run the following code:

get_ipython().run_line_magic('matplotlib', 'inline')
from nuscenes.nuscenes import NuScenes
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)

I guess the problem is in saving the datasets (v1.0-mini file), I know that I should save it under the specified dataroot but unfortunately I can not find it. can anyone help me please?

Here is the error I receive:

Traceback (most recent call last):

File "", line 3, in 
from nuscenes.nuscenes import NuScenes

File "C:\Users\haal1\tensorflow\nuscenes-devkit\python-sdk\nuscenes\nuscenes.py", line 21, in 
from nuscenes.utils.data_classes import LidarPointCloud, RadarPointCloud, Box

ModuleNotFoundError: No module named 'nuscenes.utils'; 'nuscenes' is not a package

**Comment by holger-nutonomy** [comment]
Hi, sounds like a good idea. We will look into this after CVPR.

**Comment by holger-nutonomy** [comment]
After giving this another thought, I don't think we will use it.
In particular we explicitly assign tables by name to help the IDE determine valid class members.
Otherwise the whole codebase would be sprinkled with warnings that a table's type cannot be inferred.
In my opinion this does not justify the added convenience.
Let me know if you find a way to load the tables programmatically *and* have working type hints (in Python 3.6).

**Comment by oscar-nutonomy** [comment]
@holger-nutonomy, @chocojoX : I think we can add an if-statement in `__init__`, something like this:
```
if os.path.exists(self.table_root, 'image_annotations.json'):
   self.image_annotations = self.__load_table__('image_annotations')
```
Of-course, to _really_ support this stuff, we should add existence checks to `render_sample_data` for the image modality (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L764). That also seems doable...

**Comment by holger-nutonomy** [comment]
I've just opened a PR that loads the table if it exists. However we do not plan to *really* support this stuff (rendering etc.), as many people are confused when they see the low quality of the 3d boxes projected to 2d - which is unavoidable. We encourage our users to render the accurate 3d boxes.
