### ISSUE TITLE
v1.0-mini Dataset

### ISSUE THREAD

**Issue by HazemEssamAli** [nutonomy/nuscenes-devkit#191]
Dear All,

I have downloaded the sample photos and dataset v1.0-mini and I have a question regarding the v1.0-mini dataset, more specifically in the translation and rotation of the Calibrated_Sensor, Ego_Pose and Sample_Annotation e.g. the location of the car, sensor and the bounding box.

I can get: the translation and rotation from the ego pose (for the car)
                the translation, rotation and camera intrinsic from the calibrated sensor (for the sensor)
                the translation, rotation and size from the sample annotation (for the bounding box)

I would like to draw a bounding box on the object, but unfortunately, the shared data have **no units** and they are **extremely different from each other** e.g. translation **(sample_annotation = 632.956 , 1639.65 , 1.131)** and translation **(calibrated_sensor = 1.72200568478 , 0.00475453292289 , 1.49491291905)**

According to that, I would like to ask a couple of questions:
1- Can you please let me know the units of the given coordinates?
2- How can I draw a bounding box? (it should be between the calibrated_sensor and the sample_annotation) as far as I understand, correct me if I am mistaken.
3- what is the difference between the translation and rotation and what is the camera intrinsic coordinates.

Thanks in advance,
Regards
Hazem

**Comment by oscar-nutonomy** [comment]
Dear Hazem,

thanks for your question. Next time, we ask that you please post questions on the forum: https://forum.nuscenes.org/ so that others can search and benefit from the answers.

For your questions:
1. The units are in meters. We will add that information to the https://www.nuscenes.org/data-format format page (CC @holger-nutonomy ). 
2. In terms of how to work out the geometries and renders stuff: did you look at the tutorial? It's quite extensive and would address your questions: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorial.ipynb.
3. What do you mean by difference between translation and rotation? One describes the translation and one the rotation... I'm not sure what the question is. For camera calibration refer to https://en.wikipedia.org/wiki/Camera_resectioning#Intrinsic_parameters.

**Comment by holger-nutonomy** [comment]
To add to that, the information on units (meters) and global vs. ego vehicle coordinate frames can be found in: https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md
