### ISSUE TITLE
Ego's Bounding Box

### ISSUE THREAD

**Issue by ADulian** [nutonomy/nuscenes-devkit#194]
Hi, 

Quick question, is there a way to get the bounding box of an ego's vehicle? Or if not, is there a way to estimate its velocity? Noticed that when I retrieve the bounding box of an annotation I can get all the bb data (width, height, yaw etc.) and estimate the velocity, but how would one do it for the ego vehicle?

Regards

**Comment by holger-nutonomy** [comment]
Hi
Estimating the bounding box of the ego vehicle is not trivial, but note that all cars are the same. I would just eyeball it by looking at the lidar pointcloud:
![download](https://user-images.githubusercontent.com/39502217/61860534-b436e980-aefc-11e9-8bbc-182715251110.png)

We have a function to adjust the velocity of annotations (rather than ego vehicle). You could adjust that to compute the ego vehicle velocity: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L326 But then again, once you have the ego poses and their timestamps, computing velocity is almost trivial.

For further questions, please post them at: https://forum.nuscenes.org/
