### ISSUE TITLE
rotation direction of the LiDAR 

### ISSUE THREAD

**Issue by tjucwb** [nutonomy/nuscenes-devkit#293]
Could anyone tell me the rotation direction of the Lidar in NuScenes? it rotates from the positive direction of y axis to positive direction of x axis in lidar coordinate or reverse? Thanks

**Comment by holger-nutonomy** [comment]
Hi. You can see the sensor reference frames at https://www.nuscenes.org/public/images/data.png . We generally phrase orientations as quaternions, with only minor exceptions. There are different rotations that may be of interest to you:
- The sensor orientation relative to the ego vehicle (https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#calibrated_sensor).
- The annotation's orientation in the global frame (https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#sample_annotation).
- The ego vehicle orientation in the global frame (https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#ego_pose).
In generally I recommend reusing existing code snippets, rather than figuring out the rotations yourself.

**Comment by tjucwb** [comment]
I still have a question, I want to fix the motion compensation caused by the ego pose so I want the lidar rotation direction, but I rechecked your paper again, it says that, you have done motion compensation, I want to confirm that if it means you have done motion compensation on lidar point clouds (compensate lidar measurements) to solve the inaccuracy caused by the translation and rotation of the ego car?

**Comment by holger-nutonomy** [comment]
Yes, that's exactly what it means.
You can tell because our lidar rings look like "circles" even when moving at higher speeds.
The lidar rotates clock-wise starting from the left side.
