### ISSUE TITLE
Empty annotation boxes, significant amount

### ISSUE THREAD

**Issue by 300LiterPropofol** [nutonomy/nuscenes-devkit#313]
Hi!
According to _https://github.com/nutonomy/nuscenes-devkit/blob/master/instructions.md_
In one annotation box there should be at least one lidar or one radar point.
However, in v1.0_mini dataset, there are 3466 empty annotation boxes, occupying 18.7% of total annotation number.
If I expand the bounding box size by 1.2x times, there are still 2925 empty annotation boxes, occupying 15.8%, if I expand the bounding box size by 1.5x times, there are still 2400 empty annotation boxes, occupying 12.9%.
These are significant amount of numbers and has conflict with the official statement.
Why this is happening?
PS. I check empty boxes both by calling API and simply searching in *.json file. Both have empty boxes.

**Comment by holger-nutonomy** [comment]
Hi. Note that these rules are guidelines given to the annotators. I think most of these will no longer have any lidar/radar points due to temporary occlusion. We leave it to the user to decide whether they want to use these or not. Only for the challenge we remove any boxes with 0 points (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L238).
