### ISSUE TITLE
Discrepancy between box.center and annotation coordinates

### ISSUE THREAD

**Issue by alfredrpk** [nutonomy/nuscenes-devkit#320]
I'm working on a vehicle-only motion forecasting neural network using NuScenes, so I have outputs of X and Y coordinates taken from sample annotations, as well as the ego pose X and Y coordinates for one sample. 
I'm building a visualizer tool for these outputs where I'd plot these coordinates onto a LIDAR graph. To do this, I found all the vehicle Boxes using flat coordinates for one sample.
![Image of data](https://i.imgur.com/t9JpmRb.png)
The picture above shows the first box for the first vehicle in that scene, and the first row in the preds array shows the actual coordinates for that same vehicle taken from its sample annotation translation (these will be predicted coordinates eventually, I'm using the real coordinates to test if the plotting works). I plan to make copies of these boxes and replace their box.center coordinates with the coordinates I need to plot. 
I assumed I could just edit find the displacement of the annotation coordinates from the ego pose coordinates but this seems to not give the same coordinates as that of box.center. How would I go about converting these coordinates from sample annotation translation to that of box.center's LIDAR coordinates? Does this have anything to do with the misalignment referenced in #197? 
Thank you in advance.

**Comment by alfredrpk** [comment]
Correction: the preds array listed the wrong coordinates, the first highlighted pair of coordinates should be [353.794, 1132.35]. The discrepancy is still there.

**Comment by holger-nutonomy** [comment]
Hi @alfredrpk. Note that the issue in https://github.com/nutonomy/nuscenes-devkit/issues/197 has been resolved and is only related to the map expansion. Since you didn't use that, it's not relevant here.

The ego_pose and sample_annotation tables are both in global coordinates and therefore compatible. If you want to map the boxes to the lidar coordinates, use the `get_boxes()` method (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L274). The sample_data_token needs to correspond to the token of the sample_data entry for the lidar at that sweep (`sample['data']['LIDAR_TOP']`).
