### ISSUE TITLE
render_sample_data: inaccurate bounding box

### ISSUE THREAD

**Issue by oyel** [nutonomy/nuscenes-devkit#327]
Hi,
I am just exploring your nuScenes data and I use function `nusc.render_sample_data` to visualize the label, however I find some results are obviously inaccurate, for example:
`nusc = NuScenes(version='v1.0-trainval', dataroot='/path/', verbose=True)`
`plot_sample = nusc.get('sample', '00cc708ba96a4a47b8a35118d8019bee')`
`nusc.render_sample_data(plot_sample['data']['CAM_FRONT'])`
then I would get the visualization result like this:
![image](https://user-images.githubusercontent.com/17951622/76642419-25abd100-658e-11ea-85a1-fbbcf121d034.png)
is this expected or do you have any suggestions?

Thanks a lot!

**Comment by oyel** [comment]
Some more inaccurate examples("sample_token"):
00e0e8b3e90a444783ee268d527bfa8e
00cc755c1cac4a11bac9f042e40796c0
000cf4dfaab54d21a7314036fde74966
00cf79063db9425da9be48601128a691
00d479f92c074090bfb4169d64464ee1

**Comment by jinglin80** [comment]
More issue:
![image](https://user-images.githubusercontent.com/39305807/76794901-6f6b0600-679e-11ea-87ce-63c3aaa14882.png)

**Comment by holger-nutonomy** [comment]
@oyel 
Hi, here is another view of the Jeep from above (00cc708ba96a4a47b8a35118d8019bee):
![jeep1](https://user-images.githubusercontent.com/39502217/78627106-39afcd80-78c3-11ea-8569-052075291855.png)
It is a bit hard to see, but you can see that the box tightly encloses the points (except in the front which isn't visible). I think the problem here is due to the sloped ground which makes the camera projection look wrong. Note that our boxes only have yaw, but no pitch or roll.

Please provide more details for the other examples. For `00e0e8b3e90a444783ee268d527bfa8e`, it seems like the box of the car in front of us is missing. However, note that the car does not have any lidar points, so it isn't supposed to be annotated.
![car1](https://user-images.githubusercontent.com/39502217/78627739-d1fa8200-78c4-11ea-898e-b323ca412d92.png)
![car2](https://user-images.githubusercontent.com/39502217/78627673-ad9ea580-78c4-11ea-9cac-44445c94f636.png)
![car_3](https://user-images.githubusercontent.com/39502217/78627670-abd4e200-78c4-11ea-812a-78684aabfbe9.png)

@jinglin80 
That box looks quite good in the lidar view and the two camera views. It is generally tricky to render boxes that are very close to the camera:
```
from nuscenes.nuscenes import NuScenes
nusc = NuScenes(version='v1.0-mini', verbose=True)
my_sample = nusc.get('sample', 'b993550e60054741983f8052ba97b0b0')
nusc.render_sample(my_sample['token'])
```
![download](https://user-images.githubusercontent.com/39502217/78629804-b2665800-78ca-11ea-80ea-dbf17995c86c.png)
