### ISSUE TITLE
Camera Calibration Sensor

### ISSUE THREAD

**Issue by raviy0807** [nutonomy/nuscenes-devkit#363]
In Nuscene-devkit, we are using the calibration matrix of lidar data to render point cloud on the image.
 
Any direction to understand the calibration of nuscene and how we derived these values would be helpful. 
I read the paper as well as checked the dev-kit.

1. What is the use of rotation and translation in the camera's calibration? For lidar, we require a calibration matrix to render over the image? However, I do not understand the use of camera's rotation matrix.
2. Why the rotation matrix of lidar different from the camera? 
3. Is the rotation/translation matrix of a particular sensor the same for a scene? 

Looking for understanding the calibration work

**Comment by holger-nutonomy** [comment]
Hi. I recommend you read up on the basics of camera calibration, e.g.:
http://ksimek.github.io/2012/08/22/extrinsic/
http://ksimek.github.io/2013/08/13/intrinsic/
In general there you calibrate the intrinsics (parameters of the camera) and extrinsics (where the camera is on the car). Rotation and translation are part of the extrinsics. Of course each of the 6 cameras is in a different location compared to the lidar, hence the different matrices.

Regarding your question whether the calibration settings vary across scenes: Yes due to vibrations, heat or slight inaccuracies during the mounting on different cars, there can be slight differences. Therefore we check the calibration several times per week to verify it is still good.
