### ISSUE TITLE
Bounding box projection from 3D to 2D

### ISSUE THREAD

**Issue by benemana** [nutonomy/nuscenes-devkit#457]
Hi, I used the _"export_human_2D_annotation_as_json"_ script to project all the 3D bounding boxes (visibilities = '', '1', '2', '3', '4') into 2D, and the ouptut file contains **255254** bounding boxes. But in the official documentation I found that the annotations for humans (adult, child,  construction_worker, etc.) are **222164**. So why did I get 33.090 additional bounding boxes? Shouldn't  bounding boxes be 222164 too?

Thank you.

**Comment by holger-nutonomy** [comment]
Hi. I think there are a few misunderstandings here:
- I agree that there are **222,164** human GT boxes in nuScenes trainval.
- I agree that there are **255,254** humans in the output of the script `cat /data/sets/nuscenes/v1.0-trainval/image_annotations.json | grep human | wc`.
- In fact the output contains **1,416,337** boxes: `cat /data/sets/nuscenes/v1.0-trainval/image_annotations.json | grep category_name | wc`. The expected number according to nuScenes.org is **1,166,187**. The difference is because:
  1) Some boxes don't project into any cameras and are therefore removed.
  2) Some boxes project into multiple cameras and may therefore be included twice.
