### ISSUE TITLE
how nuscenes got the velocity annotation of objects?

### ISSUE THREAD

**Issue by shouldnotfail** [nutonomy/nuscenes-devkit#505]
Hi! I am about to doing velocity estimation research on nuscenes dataset, it is very appreciated that nuscenes has the labels of velocity. But can I trust the velocity labels totally? Thanks in advance :)

**Comment by holger-nutonomy** [comment]
Hi. There are two options:
- Computing the velocity from the ego pose: Since the ego pose comes from the localization algorithm in the car, these numbers will be nicely smooth, but may be too smooth in some cases.   https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L368
- Using the measured velocity from the CAN bus: This is the "raw" data as measured by various sensors. It will be less smooth and more likely to have sudden peaks. https://www.nuscenes.org/nuscenes?tutorial=can-bus

**Comment by eriche2016** [comment]
@holger-nutonomy  Hi, I am also care about the speed of the object. I have one question: 
do you estimate the relative speed or the absolute speed of the bouding box?

**Comment by holger-nutonomy** [comment]
@eriche2016 Take a look at the code, it's really just `pos_diff / time_diff`, hence absolute speed.

**Comment by eriche2016** [comment]
Oh, I got it. Thanks for your help.

**Comment by Nan-yxchen** [comment]
@holger-motional Hi! According to your previous answer, there are two ways to calculate the target velocity: the first is based on ego_pose; the second is from CAN_bus. But I have two small questions about the 'velocity' in nuScenes.

1. How is the CAN information of the target obtained? Or here CAN_bus is used to calculate the velocity of the ego vehicle, not the target vehicle?
2. Is the velocity information of the target in the global coordinate frame?

Greatly thanks in advance!!!

**Comment by whyekit-motional** [comment]
@Nan-yxchen pls see my replies below:

1. That is correct - the CAN bus information only applies to the ego, not the agents around the ego
2. The velocity information of each agent (assuming you calculate it via [`box_velocity`](https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/nuscenes.py#L406-L408)) should be in the global coordinate frame

**Comment by Nan-yxchen** [comment]
@whyekit-motional That's very helpful! Thanks for your help
