### ISSUE TITLE
Converting from different cartesian coordinate system to global frame

### ISSUE THREAD

**Issue by micaeltchapmi** [nutonomy/nuscenes-devkit#549]
Hi,

Thanks for this great dataset. I have an object in a cartesian coordinate system which I would like to align to that of a point cloud in the global frame. After converting the pointcloud to global coordinates(1st and 2nd steps in map_pointcloud_to_image), I found that it's orientation is different from that of my object and I'm not sure how to get them to align in the global frame. Can you help me understand how to go about doing this?

Thank you!

Micael

**Comment by holger-nutonomy** [comment]
Hi. 
You are exactly right that you can use the 1st and 2nd steps in https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L782. Since these have been thoroughly tested I guess the error must be in your transformation of the object. What coordinate system is your object originally defined in? Is it relative to the ego vehicle?

**Comment by micaeltchapmi** [comment]
Hi @holger-nutonomy,

Thanks for your quick reply. The object is not defined relative to the ego vehicle. Assuming the object is in a coordinate system defined by a modeling tool such as Blender, how would I go about aligning its orientation to your system's global frame?
