### ISSUE TITLE
I would like to get the (x,y,z) coordinates of of the ego vehicle.

### ISSUE THREAD

**Issue by Ravindradhanapal** [nutonomy/nuscenes-devkit#56]
as I am working on collision avoidance paper I would like to get the true data ie,  x,y,z co-ordinates for all the scenes available could you help me out with the same.

**Comment by holger-nutonomy** [comment]
Hi. What do you mean by true data? You can get the ego vehicle coordinates (world coordinates) in meters from the `ego_vehicle` table's `translation` in the [database](https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md). The reference (0, 0, 0) is the point at the top left corner of the respective map. Take a look at [this function](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L985) which visualizes ego poses on the map. In the future we will add the formula for converting that into lat/lon coordinates.

Let me know if that answers your questionsl

**Comment by zhangpur** [comment]
Hi,
I have the similar concerns of this problem: Does `translation` in `ego_pose` exactly mean the position of the centre of the ego vehicle? Sorry if it sounds like a silly question. It's just for verifying, as localization algorithm is not given in detail. 
For the task of collision avoidance,  size of ego vehicle is also needed. Do you have any reference measurements about this? @holger-nutonomy

**Comment by holger-nutonomy** [comment]
@zhangpur The reference is the IMU which is located roughly at the center of the rear axle. I think you can use the vehicle size available online: https://en.wikipedia.org/wiki/Renault_Zoe (of course it does not include the additional height due to the lidar).

**Comment by zhangpur** [comment]
Thanks, very helpful.

**Comment by ray401** [comment]
hi,  why the reference is the IMU which is located roughly at the center of the rear axle instead of the center of rear axle projected on the ground ?
--------
for example, if i want to get the location of  a lidar point in world coordinate,  firstly i need to use "translation" and "rotation" in calibrated_sensor.json to project it to ego vehicle system, then use "translation" and "rotation" in ego_pose.json file to project to world coordinate system.
am i right ?
--------
if the origin of  ego vehicle system is on the center of rear axle , then it has a distance deviation in z zxis.  

@holger-nutonomy

**Comment by ray401** [comment]
in addition, i want to know the orientation of the ego system ? is  the orientation of ego coordinate  consistent with the orientation of imu coordinate ?



@holger-nutonomy
