### ISSUE TITLE
[Question] Information about LiDAR mounting position and data sheet

### ISSUE THREAD

**Issue by ltriess** [nutonomy/nuscenes-devkit#618]
Hi, thanks for the great devkit. I have two questions:

1. I cannot find the exact mounting position of the LiDAR sensor in the documents. Specifically, I am interested in the height above ground. I see that this was somehow mentioned [here](https://github.com/nutonomy/nuscenes-devkit/issues/56#issuecomment-558555994) already, however it only states the height of the ego-vehicle roof and not the LiDAR mounting position.

2. Maybe I missed it, but I wasn't able to see a link on the website that points to the technical data sheet of the exact LiDAR sensor that was used to capture the dataset. Since it is a Velodyne VLP-32, I was wondering if [this site](https://velodynelidar.com/products/ultra-puck/) contains the information about the same sensor as used for nuScenes.

Thanks for your help.

**Comment by vobecant** [comment]
Hi, I would also like to thank you for the dataset and for this devkit. I am interested in the same questions as @ltriess and I would like to ask one more:
What are the exact parameters of the LiDAR sensor (the top one) used to capture the data? 
I would like to get a range image (raw recording of the LiDAR sensor) in order to use in another task. I don't think that you provide the raw range images but that you provide the 3d points straight away.
There might exist some methods that would map the 3d points back to the range image but I need to know the parameters of the LiDAR sensor to be able to use them. Most importantly, I would need to know the vertical and horizontal angles between the LiDAR beams.
Thank you very much in advance.

**Comment by whyekit-motional** [comment]
Hi @ltriess and @vobecant, 

We provide the extrinsics of the lidar, which you can obtain by doing something like:
```
from nuscenes.nuscenes import NuScenes


nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)

my_scene = nusc.scene[0]
first_sample_token = my_scene['first_sample_token']

my_sample = nusc.get('sample', first_sample_token)
lidar_top_data = nusc.get('sample_data', my_sample['data']['LIDAR_TOP'])

print(nusc.get('calibrated_sensor', lidar_top_data['calibrated_sensor_token']))
```
The extrinsics are with respect to the rear axle (referencing [here](https://github.com/nutonomy/nuscenes-devkit/issues/56#issuecomment-558555994)), so you can trivially calculate the position of the lidar.

As for the lidar data sheet, pls send an email to nuscenes@motional.com. 

Hope these answer your questions!

**Comment by ltriess** [comment]
Thanks
