### ISSUE TITLE
How to train ‘v1.0-trainval01_blobs_lidar’

### ISSUE THREAD

**Issue by liuwenlei2018** [nutonomy/nuscenes-devkit#664]
I’m first to use the nuSenes-Data, it’s feel good. I can train ‘v1.0-mini’, but when training the ‘v1.0-trainval01_blobs_lidar’, it shows that ’sets/nuscenes/samples/LIDAR_TOP/n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603547590.pcd.bin’ in val_dataset_loader. I check the samples datas and the sweeps data, which miss the ‘n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603547590.pcd.bin’.
How to use the  ‘v1.0-trainval01_blobs_lidar’ to train? whether I miss some file or I should modify the codes? 
Thank you!

**Comment by whyekit-motional** [comment]
This is because the files for the `trainval` split are distributed across the 10 archives (for convenience of download). As an example, the file which you are referring to (`n008-2018-08-01-15-16-36-0400__LIDAR_TOP__1533151603547590.pcd.bin`) is contained within `v1.0-trainval02_keyframes.tgz`.

Generally, you should download all 10 archives and then combine them before use.

**Comment by liuwenlei2018** [comment]
I see. Thank you very much!

**Comment by whyekit-motional** [comment]
@LIvanoff you would probably have to hack the devkit code to work on only one blob
