### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by TianhaoFu** [nutonomy/nuscenes-devkit#705]
Hi,
Thanks your repo, nice work.
I have some questions:
- Is the point cloud data positive？ or will there be negative numbers？
- What's the max and min value of 3D Bounding box size [w,l,h]?
- Bounding box location center correspond to points on the point cloud？or do they not necessarily correspond to points on the point cloud？

**Comment by whyekit-motional** [comment]
@TianhaoFu with regards to your various questions:

- Is the point cloud data positive？ or will there be negative numbers？
   - Yes, there can be negative numbers (e.g. for x, y,z) since the coordinates given in the point cloud data is wrt the ego.
- What's the max and min value of 3D Bounding box size [w,l,h]?
  - This depends on which split you are looking to the get the max and min of (e.g. `train`, `val`, `mini`, etc.). However, whichever split you are interested in, it should be trivial to loop over the sample annotations and get the max of the widths, lengths and heights, e.g.:
  ```
  import numpy as np

  from nuscenes.nuscenes import NuScenes


  # Load the nuScenes dataset (mini-split, in this case).
  nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

  sizes = [sample_ann['size'] for sample_ann in nusc.sample_annotation]
  print(np.max(sizes, axis=0))
  ```
- Bounding box location center correspond to points on the point cloud？or do they not necessarily correspond to points on the point cloud？
  - No, the center of a bbox does not necessarily correspond to a point on the point cloud
