### ISSUE TITLE
Inconsistency between map masks and layers

### ISSUE THREAD

**Issue by gobear6212** [nutonomy/nuscenes-devkit#747]
Earlier today I was trying to plot the map mask of drivable area with `map_api.render_map_mask()` for the whole boston-seaport, but then I found that part of it is missing. However, it doesn't happen if I use `map_api.render_layers()` instead (see attached).
- `map_api.render_map_mask()`
![Unknown](https://user-images.githubusercontent.com/85070296/162879325-e2c4526f-c3b7-47fd-8184-b56621b2ddc7.png)
- `map_api.render_layers()`
![Unknown-2](https://user-images.githubusercontent.com/85070296/162879430-0ebcfb90-b45b-4021-aba4-0eb2b14ba64a.png)

Hence, I would like to know how can I ensure that `map_api.get_map_mask()` actually returns the correct sets of points for the whole map?

**Comment by whyekit-motional** [comment]
@gobear6212 thanks for pointing this out - I am able to replicate this issue on my end too

I believe the cause of this arises from this: https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/map_expansion/map_api.py#L1825-L1826

The mask is generated by sequentially adding each polygon onto a "canvas". Thus, when a polygon with holes gets added on, any previous polygons that fall within the holes get wiped out due to the code snippet above. As an example (the images from left to right depict the process of adding a single polygon onto the "canvas" each time):
 <td colspan="x">
      <table>
          <tr>
              <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/163096314-014aa402-5da1-4e7e-afc3-b40bc04f3845.png" alt="mask1" width="400"/></td>
              <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/163096313-c9a61eec-3b2a-4112-b8dd-aba74d0a047d.png" alt="mask2" width="400"/></td>
               <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/163096311-da339072-5249-492f-9dd6-45870bb85adb.png" alt="mask3" width="400"/></td>
          </tr>
      </table>
</td>

For anyone interested in observing this process of sequentially adding polygons to a "canvas" to generate the mask, the above can be reproduced via:

1. Add these lines of code within the loop in `_polygon_geom_to_mask` [here](https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/map_expansion/map_api.py#L1890):
   ```
   plt.imshow(map_mask)
   plt.show()
   ```
   That should give:
   ```
   for polygon in layer_geom:
      new_polygon = polygon.intersection(patch)
         if not new_polygon.is_empty:
            ...
            plt.imshow(map_mask)
            plt.show()

   return map_mask
   ```
2. Run this:
   ```
   from nuscenes.map_expansion.map_api import NuScenesMap


   nusc_map = NuScenesMap(dataroot='/data/sets/nuscenes', map_name='boston-seaport')

   map_mask = nusc_map.get_map_mask(patch_box=(1782, 850, 300, 300), 
                                    patch_angle=0, 
                                    layer_names=['drivable_area'], 
                                    canvas_size=None)
   ``` 

A possible way to fix this would be to replace the existing `mask_for_polygons` [here](https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/map_expansion/map_api.py#L1810) with:
```
@staticmethod
def mask_for_polygons(polygons: MultiPolygon, mask: np.ndarray) -> np.ndarray:
   """
   Convert a polygon or multipolygon list to an image mask ndarray.
   :param polygons: List of Shapely polygons to be converted to numpy array.
   :param mask: Canvas where mask will be generated.
   :return: Numpy ndarray polygon mask.
   """
   if not polygons:
      return mask

   # Create a temporary canvas for the current polygon.
   canvas_size = mask.shape
   tmp_mask = np.zeros(canvas_size, np.uint8)

   def int_coords(x):
      # function to round and convert to int
      return np.array(x).round().astype(np.int32)
   exteriors = [int_coords(poly.exterior.coords) for poly in polygons]
   interiors = [int_coords(pi.coords) for poly in polygons for pi in poly.interiors]

   # cv2.fillPoly(mask, exteriors, 1)
   # cv2.fillPoly(mask, interiors, 0)

   # Fill in the canvas with the current polygon
   cv2.fillPoly(tmp_mask, exteriors, 1)
   cv2.fillPoly(tmp_mask, interiors, 0)

   # Convert the masks from a binary (uint8) to a boolean one.
   tmp_mask = np.ma.make_mask(tmp_mask)
   mask = np.ma.make_mask(mask)

   # Merge the two masks using an OR operation, to prevent previous polygons from 
   # being blanked out if the current polygon has holes and they fall within those 
   # holes.
   mask = np.ma.mask_or(mask, tmp_mask)
   
   # Convert the boolean mask back to a binary (uint8) one.
   mask = mask.astype(np.uint8)

   return mask
```

Now, if you re-run step 2 from above, you would be able to see:
 <td colspan="x">
      <table>
          <tr>
               <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/163099737-6174c548-2e90-49a8-8988-dfbca32491c6.png" alt="mask1_fixed" width="400"/></td>
              <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/163099734-01826f47-45c9-4837-add4-7942d12849ab.png" alt="mask2_fixed" width="400"/></td>
              <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/163099726-593589fc-85c7-4231-b277-3eef5ddd0b3c.png" alt="mask3_fixed" width="400"/></td>
          </tr>
      </table>
</td>

Now, if you view the entire map mask, it should be ok:
```
import matplotlib.pyplot as plt


map_mask = nusc_map.get_map_mask(patch_box=None, 
                                 patch_angle=0, 
                                 layer_names=['drivable_area'], 
                                 canvas_size=None)[0]

fig = plt.figure(figsize=(15, 15))

plt.imshow(map_mask)
plt.show()
```
![map_fixed](https://user-images.githubusercontent.com/62535720/163100741-60527f03-5e31-40f6-b97f-c5c706388d54.png)
