### ISSUE TITLE
question about the corners() method of Box class

### ISSUE THREAD

**Issue by ideasplus** [nutonomy/nuscenes-devkit#752]
Hi, 

I have a question about the generation of  3d box corners.
https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/utils/data_classes.py#L612-L619

 According to the code, the xyz direction of the initial corners are front, left and up no matter what the sensor frame. The orientation of box has transform to the local sensor frame, why can we use `corners = np.dot(self.orientation.rotation_matrix, corners)` to get the correct  result? Should we define the corners in the sensor frame and use the yaw of the box to get the final result? 

I'm also confused by the orientation of the box. Please see the following code. I use a car as a example. 

![nuscene_screenshot_23 04 2022](https://user-images.githubusercontent.com/24294571/164883986-6664d25b-25da-4e96-a7a5-c0477fb49fef.png)

```
cam_front_token = 'a61bfbde6877413386a772591617f38d'
sample_annotations_token = 'fb5169ad9daa4d1086ec59d6cf5ed4b0'
_, box_camera, _ = nusc.get_sample_data(cam_front_token, selected_anntokens=[sample_annotations_token])
angles_box_camera = np.array(box_camera[0].orientation.yaw_pitch_roll) / np.pi * 180
print('box orientation in camera frame: ', angles_box_camera)
```
the output is `box orientation in camera frame:  [120.46844792   1.10142931  91.32124014]`

The yaw of the car in camera frame should be negative, the roll and pitch should be close to zero. However, the output isn't satisfied but I still get the correct plot using the `corners()` method. I must be misunderstanding something, please let me know the reason.

**Comment by whyekit-motional** [comment]
@ideasplus hopefully these clears up your doubts:

1. > According to the code, the xyz direction of the initial corners are front, left and up no matter what the sensor frame.

   This is not true - the boxes are stored in the global coordinate frame (otherwise, there would need to be multiple entries in the database for the same box in different sensor frames!) and hence `corners = np.dot(self.orientation.rotation_matrix, corners)` is needed to be done to transform them to the sensor frame.


2. > The yaw of the car in camera frame should be negative, the roll and pitch should be close to zero.

   Note that for `CAM_FRONT`, the x-axis points to the right of the ego, the y-axis points down into the ego, and the z-aixs point to the front on the ego (take a look at the coordinate frames of the various sensors [here](https://www.nuscenes.org/static/media/data.9ef46c59.png)). With that in mind, that should help you to figure out why the yaw of the car for `CAM_FRONT` is positive, and why the roll is not close to 0.
