### ISSUE TITLE
the range of the tracking groundtruth

### ISSUE THREAD

**Issue by wudaye666** [nutonomy/nuscenes-devkit#781]
the range used during evaluation is 0~40 or 0~50.
but how far will nuscenes mark the groundtruth.
whether the obstacle out of the range of groundtruth marked will be considerder as fp?

**Comment by wudaye666** [comment]
the class_range is 40 or 50

**Comment by whyekit-motional** [comment]
@wudaye666 do take a look at the following part of the script for tracking evaluation: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/tracking/evaluate.py#L94-L100

Both the inferred and ground truth boxes are filtered based on distance (among other things), so inferred boxes which are out of range are not considered FPs since they are filtered out during evaluation
