### ISSUE TITLE
Using ground truth as predictions does not give perfect result on detection benchmark

### ISSUE THREAD

**Issue by zmurez** [nutonomy/nuscenes-devkit#807]
I would expect that using the ground truth labels as predictions would give perfect results on the detection benchmark, but I found that mAP and NDS are less than 1.

Here are the results of doing this on the mini_val set
```
Per-class results:
Object Class	AP	ATE	ASE	AOE	AVE	AAE
car	0.824	0.000	0.000	0.000	0.000	0.000
truck	1.000	0.000	0.000	0.000	0.000	0.000
bus	1.000	0.000	0.000	0.000	0.000	0.000
trailer	0.000	1.000	1.000	1.000	1.000	1.000
construction_vehicle	0.000	1.000	1.000	1.000	1.000	1.000
pedestrian	0.937	0.000	0.000	0.000	0.000	0.000
motorcycle	0.981	0.000	0.000	0.000	0.000	0.000
bicycle	0.660	0.000	0.000	0.000	0.000	0.000
traffic_cone	0.895	0.000	0.000	nan	nan	nan
barrier	0.000	1.000	1.000	1.000	nan	nan
```

The results for categories not represented in the min_val set are not surprising. But `["car", "pedestrian", "motorcycle", "bicycle", "traffic_cone"]` which have AP<1 is surprising.

Code to reproduce:
```import json

from nuscenes import NuScenes
from nuscenes.eval.detection.evaluate import NuScenesEval
from nuscenes.eval.common.config import config_factory
from nuscenes.eval.common.loaders import load_gt
from nuscenes.eval.detection.data_classes import DetectionBox



def main():
    result_path = 'temp/nuscenes_eval.json'
    output_dir = 'temp/nuscenes_eval'
    version = 'v1.0-mini'
    version_set = 'mini_val'
    

    nusc = NuScenes(version=version, dataroot='/mnt/local/NuScenes', verbose=False)

    # make perfect predictions by loading GT
    data=load_gt(nusc, version_set, DetectionBox, verbose=True)
    results = {
        "meta": {"use_lidar": False, "use_camera": True, "use_radar": False, "use_map": False, "use_external": False},
        "results": {}
    }
    for token in data.sample_tokens:
        results['results'][token] = []
        for ann in data[token]:
            results['results'][token].append({
                "sample_token": token,
                "translation": ann.translation,
                "size": ann.size,
                "rotation": ann.rotation,
                "velocity": ann.velocity.tolist(),
                "detection_name": ann.detection_name,
                "detection_score": 1.,
                "attribute_name": ann.attribute_name 
            })

    json.dump(results, open(result_path, 'w'))


    # do evaluation
    nusc = NuScenes(version=version, dataroot='/mnt/local/NuScenes', verbose=False)
    eval_detection_config = config_factory('detection_cvpr_2019')
    nusc_eval = NuScenesEval(
        nusc,
        config=eval_detection_config,
        result_path=result_path,
        eval_set=version_set,
        output_dir=output_dir,
        verbose=False)
    nusc_eval.main(render_curves=False)

main()```

**Comment by whyekit-motional** [comment]
@zmurez you should not simply save save every box since [there are boxes within the dataset which do not contain lidar / radar points](https://github.com/nutonomy/nuscenes-devkit/blob/master/README.md#known-issues):
```
A small number of 3d bounding boxes is annotated despite the object being temporarily occluded.
```
It would be unfair to expect a model to produce those detection, when there isn't a single point at that location. 

For this reason, during evaluation, one of the [preprocessing steps](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection#preprocessing) is to remove ground-truth boxes without lidar or radar points (pls see the [code](https://github.com/nutonomy/nuscenes-devkit/blob/9b209638ef3dee6d0cdc5ac700c493747f5b35fe/python-sdk/nuscenes/eval/common/loaders.py#L231) for details)

Thus, if you simply save every box from `load_gt` as a "prediction", the "predicted" boxes which have zero points in them will become False Positives (resulting in AP < 1). 

Instead, when saving the ground-truth boxes as "predictions", you should skip over boxes which have no points, e.g.:
```
# make perfect predictions by loading GT
data = load_gt(nusc, version_set, DetectionBox, verbose=True)
results = {
    "meta": {"use_lidar": False, "use_camera": True, "use_radar": False, "use_map": False, "use_external": False},
    "results": {}
}
for token in data.sample_tokens:
    results['results'][token] = []
    for ann in data[token]:
      if ann.num_pts != 0:  # Skip over annotations which have zero points.
        results['results'][token].append({
            "sample_token": token,
            "translation": ann.translation,
            "size": ann.size,
            "rotation": ann.rotation,
            "velocity": ann.velocity.tolist(),
            "detection_name": ann.detection_name,
            "detection_score": 1.,
            "attribute_name": ann.attribute_name
        })
```

Subsequently, if you run the detection evaluation, you should be able to see a perfect AP for the various classes:
```
Object Class      AP    ATE   ASE   AOE   AVE   AAE
car   1.000 0.000 0.000 0.000 0.000 0.000
truck 1.000 0.000 0.000 0.000 0.000 0.000
bus   1.000 0.000 0.000 0.000 0.000 0.000
trailer     0.000 1.000 1.000 1.000 1.000 1.000
construction_vehicle    0.000 1.000 1.000 1.000 1.000 1.000
pedestrian  1.000 0.000 0.000 0.000 0.000 0.000
motorcycle  1.000 0.000 0.000 0.000 0.000 0.000
bicycle     1.000 0.000 0.000 0.000 0.000 0.000
traffic_cone      1.000 0.000 0.000 nan   nan   nan
barrier     0.000 1.000 1.000 1.000 nan   nan
```

**Comment by zmurez** [comment]
Good catch. Thanks!

**Comment by zmurez** [comment]
Although this means that a powerful model that can track through occlusions would get penalized for this... We should probably filter the annotations at training time too, and teach the model to not predict occluded objects.

**Comment by whyekit-motional** [comment]
@zmurez a detection model, no matter how powerful, will never be able to predict the presence of an object at a location where there are no points.

However, a tracking model might be able to do so. As such, when it comes to the tracking task, the boxes which were filtered out due to having zero points in them are recovered via this method:
https://github.com/nutonomy/nuscenes-devkit/blob/9b209638ef3dee6d0cdc5ac700c493747f5b35fe/python-sdk/nuscenes/eval/tracking/loaders.py#L56-L58

Subsequently, there will be ground truth boxes available for evaluation even though there is an occlusion. Thus, a (tracking) model which is able to track through the occlusions will **not** be penalized.
