### ISSUE TITLE
Questions about temporal occlusion for labelling and tracking

### ISSUE THREAD

**Issue by yuhb94** [nutonomy/nuscenes-devkit#808]
Hi, thanks for your great dataset! 

I notice there are some labelled objects that are totally occluded and there are no lidar points in them. The visualization could be seen the second picture below. And you also note that "A small number of 3d bounding boxes is annotated despite the object being temporarily occluded. For this reason we make sure to filter objects without lidar or radar points in the nuScenes benchmarks. See https://github.com/nutonomy/nuscenes-devkit/issues/366.".
![图片](https://user-images.githubusercontent.com/19658242/183855197-1822ee6d-3554-48b3-a6be-f54c1b80de0c.png)
![图片](https://user-images.githubusercontent.com/19658242/183855276-7e054fbf-3628-4a7b-8386-8b80f179c9e9.png)
![图片](https://user-images.githubusercontent.com/19658242/183855245-2217b63f-b50b-488a-81c1-f999e96850ac.png)

There are two questions:
1.  Since the objects are totally occluded, how do you label the occluded 3D objects?
2.  Do you regard the occluded trajectory as one trajectory or two trajectories with different tracking ID in tracking task?

Many thanks!

**Comment by whyekit-motional** [comment]
@yuhb94 I hope these will clear up your queries:

- > Since the objects are totally occluded, how do you label the occluded 3D objects?

The annotation tooling used in nuScenes can show all cameras, lidars and radars for the 20-secs scene. Objects are annotated with interpolation. That means that if an object can be seen at 1 secs and at 3 secs, the frames in between are linearly interpolated, even if the object is occluded (note that for evaluation purposes, boxes without lidar/radar points are removed, as there is no chance for a detector to detect these). Of course there can be all kinds of exceptions, e.g. often you see an object through the window of a car, but may not get lidar returns from it.

- > Do you regard the occluded trajectory as one trajectory or two trajectories with different tracking ID in tracking task?

Each instance is treated as a single track / trajectory:
https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/common/loaders.py#L146
