### ISSUE TITLE
Clarification regarding timesteps

### ISSUE THREAD

**Issue by ekosman** [nutonomy/nuscenes-devkit#821]
Hello,

I want to use the prediction extension of nuscenes, however I encounter a little misunderstanding of the returned values I get from `get_future_for_sample` and `get_past_for_sample`. To my understanding, the result does not contain the record for timestep 0, e.g. setting `seconds=1` would result with 2 record that correspond to timesteps 0.5 and 1. How can one get the record for timestep 0?

**Comment by whyekit-motional** [comment]
@ekosman yes, you are right that `get_future_for_sample` and `get_past_for_sample` do not return the record for the current timestep (as seen in the code [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/prediction/helper.py#L139))

If you want the record for the current timestamp, you could simply do:
```
from nuscenes import NuScenes
from nuscenes.prediction import PredictHelper


nuscenes = NuScenes('v1.0-mini', dataroot='/data/sets/nuscenes')
helper = PredictHelper(nuscenes)

sample_token = '39586f9d59004284a7114a68825e8eec'
sample = helper.get_annotations_for_sample(sample_token)
```
The above gives a list of agents at the current timestamp, e.g.:
```
[...,
 {'token': 'f0cbd9dbafd74e20bcf6dd0357c97f59',
  'sample_token': '39586f9d59004284a7114a68825e8eec',
  'instance_token': 'bd26c2cdb22d4bb1834e808c89128898',
  'visibility_token': '1',
  'attribute_tokens': ['c3246a1e22a14fcb878aa61e69ae3329'],
  'translation': [353.776, 1132.363, 0.622],
  'size': [2.011, 4.633, 1.573],
  'rotation': [0.9797276292877292, 0.0, 0.0, -0.20033415188191459],
  'prev': '924ee6ac1fed440a9d9e3720aac635a0',
  'next': '8990cacb0c5a4d43b4b2112c101e4274',
  'num_lidar_pts': 0,
  'num_radar_pts': 0,
  'category_name': 'vehicle.car'},
...]
```
You can then match the `instance_token` for each agent to the `dict` returned by `get_future_for_sample` / `get_past_for_sample` (since the key is the instance token of an agent in the sample)
