### ISSUE TITLE
how can I draw the 3d boxes in lidar frame after inference on camera frame?

### ISSUE THREAD

**Issue by jiaminglei-lei** [nutonomy/nuscenes-devkit#822]
I got some 3d boxes in lidar frame after inference. I tried to visualize them on camera frame, but I failed.
I follow the function `map_pointcloud_to_image` and transform them like 'lidar -> ego -> global -> ego -> camera'. However, it doesn't work.
could you give me some idea? thank you.

**Comment by whyekit-motional** [comment]
@jiaminglei-lei here's one possible approach:

1. Change these lines in `get_sample_data` to give your inferred boxes, rather than the ground truth: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/nuscenes.py#L280-L283
2. Then you can use this portion of `render_sample_data` as it is, to render your inferred boxes in the camera frame: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/nuscenes.py#L1437-L1457

**Comment by jiaminglei-lei** [comment]
@whyekit-motional  thanks for your help. 
I just followed the function `map_pointcloud_into_image` and obtained the results. thank you.
