### ISSUE TITLE
yaw definition in camera coordinate system

### ISSUE THREAD

**Issue by zhulinzhang** [nutonomy/nuscenes-devkit#843]
As in followed link, mmdetection3d uses the negative of yaw when converting to nuscenes-format bbox in camera cooridnate system. Does nuscenes define yaw in camera coordinate system in another fashion?
[https://github.com/open-mmlab/mmdetection3d/blob/962fc830daebad3f93fc7cbf970728057c64977b/mmdet3d/datasets/nuscenes_mono_dataset.py#L713](url)

Considering following scenario, an object in front of a camera driving towards, in mmdetection3d the yaw should be negative 0.5pi. Is it negative 0.5pi in nuscenes?

**Comment by whyekit-motional** [comment]
@zhulinzhang in nuScenes, the boxes are given with respect to the global coordinate frame (see [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#sample_annotation)) 

If you do transform them to the coordinate frame of a specific camera, then - in your example scenario of an object driving towards the camera - you should be looking at the pitch in the camera's coordinate frame (since for the various cameras, the y-axis is pointing downwards into the ego, as shown in https://www.nuscenes.org/public/images/data.png)
