### ISSUE TITLE
Regarding the Radar Velocity data

### ISSUE THREAD

**Issue by boazMgm** [nutonomy/nuscenes-devkit#868]
Hi,
In the radar .PCD files, there are a few fields regarding velocity of the detections.
I'm trying to understand the relationship between vx and vx_comp, and between vy and vy_comp.
from looking on past issues, I see that the vx_comp is the velocity of the detection on the x axis after compensating the velocity of the vehicle's ego velocity on the x axis, so I understand that the following relationship should hold:
vx_comp = vx-vx_ego
vy_comp = vy-vy_ego

but if that true, then for a specific PCD file I should get the same vx_ego and vy_ego for all detections:
vx_ego = vx-vx_comp
vy_ego - vy-vy_comp

but when I do the calculation I don't get the same numbers.
So, I'm trying to understand the true relationship between these values and in particular
extract the doppler information in m/s units.

Thanks

**Comment by whyekit-motional** [comment]
@boazMgm the numbers wouldn't be exactly the same since the radar data, like most real-world measurements, is noisy

In addition, do note that `vx` and `vy` (from [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L329)) refer to the component velocities relative to the radar, not the absolute velocity (velocity relative to the ground)
