### ISSUE TITLE
Comments of issues #879 and #880 

### ISSUE THREAD

**Issue by AngelosSE** [nutonomy/nuscenes-devkit#881]
The issues #879 and #880 have been closed, but I have made comment to them requesting further help. I am writing this in case closed issues do not generate notifications. I have never used this issue-handling system before and I am sorry for any inconvenience the creation of this "pointer" issue may bring.

**Comment by whyekit-motional** [comment]
@AngelosSE no worries, I'll reply you in the respective issues to keep things neat and consolidated

I have received email notifications from GitHub for #879 and #880, but I may take some time to respond due to work commitments :sweat_smile:

In the meantime, I'll close this issue as it is not directly related to the repo or the data of nuScenes
